### ISSUE TITLE
Git - wie gehe ich mit secrets um?

### ISSUE THREAD

**Issue by aaronbach** [aaronbach/web-dev-coffee-talk#23]
Keine Secrets in git? Wie bekommen neue Teammitglieder ihre credentials? 

Mögliche Lösung:
https://github.com/sobolevn/git-secret
https://github.com/thebitrebels/git-tresor

**Comment by jonathanheilmann** [comment]
https://github.com/aaronbach/web-dev-coffee-talk/commit/459c21f88909dbe7cf73544e7a059229dcc78ceb
